# Generated by Django 5.2.9 on 2025-12-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="editor_preference",
            field=models.CharField(
                choices=[
                    ("myst_markdown", "MyST Markdown"),
                    ("rich_text", "Rich Text (Quill)"),
                ],
                default="myst_markdown",
                max_length=20,
            ),
        ),
    ]
