# Generated by Django 5.2.9 on 2025-12-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_profile_username_friendrequest_friendship_invitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="birthday",
            field=models.DateField(
                blank=True, help_text="Birthday for zodiac sign calculation", null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="city",
            field=models.CharField(
                blank=True, help_text="City name for weather data", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="country_code",
            field=models.CharField(
                blank=True,
                default="US",
                help_text="Two-letter country code",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="horoscope_enabled",
            field=models.BooleanField(
                default=False, help_text="Enable horoscope-based insights"
            ),
        ),
    ]
