# Generated by Django 5.2.9 on 2025-12-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0004_profile_birthday_profile_city_profile_country_code_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="subscription_tier",
            field=models.CharField(
                choices=[("free", "Free"), ("premium", "Premium")],
                default="free",
                help_text="User's subscription tier",
                max_length=20,
            ),
        ),
    ]
