# Generated by Django 5.2.9 on 2025-12-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_payment_subscriptionhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="stripe_customer_id",
            field=models.CharField(
                blank=True, help_text="Stripe customer ID", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="stripe_subscription_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe subscription ID",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="subscription_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="subscription_plan",
            field=models.CharField(
                blank=True,
                choices=[
                    ("individual_monthly", "Individual - Monthly ($10/mo)"),
                    ("individual_yearly", "Individual - Yearly ($100/yr)"),
                    ("family_monthly", "Family - Monthly ($20/mo)"),
                    ("family_yearly", "Family - Yearly ($200/yr)"),
                ],
                help_text="Selected subscription plan",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="subscription_start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="subscription_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("active", "Active"),
                    ("canceled", "Canceled"),
                    ("past_due", "Past Due"),
                    ("incomplete", "Incomplete"),
                    ("trialing", "Trialing"),
                ],
                help_text="Stripe subscription status",
                max_length=20,
                null=True,
            ),
        ),
    ]
