# Generated by Django 5.2.9 on 2025-12-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_profile_stripe_customer_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="privacy_accepted",
            field=models.BooleanField(
                default=False, help_text="User accepted Privacy Policy"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="privacy_accepted_at",
            field=models.DateTimeField(
                blank=True, help_text="When privacy policy was accepted", null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="terms_accepted",
            field=models.BooleanField(
                default=False, help_text="User accepted Terms of Service"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="terms_accepted_at",
            field=models.DateTimeField(
                blank=True, help_text="When terms were accepted", null=True
            ),
        ),
    ]
