# Generated by Django 5.2.9 on 2025-12-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0008_profile_privacy_accepted_profile_privacy_accepted_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="devotion_enabled",
            field=models.BooleanField(
                default=False, help_text="Enable daily Christian devotions"
            ),
        ),
    ]
