# Generated by Django 5.2.9 on 2025-12-28 01:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_familymember"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="familymember",
            new_name="accounts_fa_admin_i_8d25c8_idx",
            old_name="accounts_fa_admin_i_7e4c6a_idx",
        ),
        migrations.RenameIndex(
            model_name="familymember",
            new_name="accounts_fa_member__705e52_idx",
            old_name="accounts_fa_member__3fa1de_idx",
        ),
        migrations.AddField(
            model_name="profile",
            name="temperature_unit",
            field=models.CharField(
                choices=[("C", "Celsius"), ("F", "Fahrenheit")],
                default="F",
                help_text="Preferred temperature unit",
                max_length=1,
            ),
        ),
    ]
