# Generated by Django 5.2.9 on 2025-12-28 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_add_user_badge"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("bug", "Bug Report"),
                            ("idea", "Feature Idea"),
                            ("other", "Other"),
                        ],
                        default="bug",
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "page_url",
                    models.URLField(
                        blank=True,
                        help_text="The page the user was on when submitting feedback",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("reviewed", "Reviewed"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, help_text="Internal notes from admin"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="accounts_fe_user_id_92821f_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="accounts_fe_status_b8d99b_idx",
                    ),
                    models.Index(
                        fields=["feedback_type", "-created_at"],
                        name="accounts_fe_feedbac_9324c2_idx",
                    ),
                ],
            },
        ),
    ]
