# Generated by Django 5.2.9 on 2025-12-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_add_feedback_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="enable_cycle_tracking",
            field=models.BooleanField(
                default=False, help_text="Enable menstrual cycle tracking"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="enable_intimacy_tracking",
            field=models.BooleanField(
                default=False, help_text="Enable special moments (🍀) tracking"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Prefer not to say"),
                    ("male", "Male"),
                    ("female", "Female"),
                    ("other", "Other"),
                ],
                default="",
                help_text="Gender for wellness feature customization",
                max_length=10,
            ),
        ),
    ]
