# Generated by Django 5.2.9 on 2025-12-31 02:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_add_wellness_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="encryption_salt",
            field=models.BinaryField(
                blank=True,
                help_text="Per-user salt for encryption key derivation",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="encryption_version",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="0=global key, 1=per-user key"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="key_derivation_iterations",
            field=models.PositiveIntegerField(
                default=600000, help_text="PBKDF2 iterations for key derivation"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="recovery_key_hash",
            field=models.CharField(
                blank=True,
                help_text="SHA-256 hash of recovery key for password reset",
                max_length=128,
                null=True,
            ),
        ),
    ]
