# Generated by Django 5.2.9 on 2026-01-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_add_encryption_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="tutorial_completed",
            field=models.BooleanField(
                default=False,
                help_text="Whether user has completed the onboarding tutorial",
            ),
        ),
    ]
