# Generated by Django 5.2.9 on 2025-12-22 03:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("journal", "0002_attachment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        default="bi-check-circle",
                        help_text="Bootstrap icon class (e.g., bi-heart, bi-book)",
                        max_length=50,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#4f46e5", help_text="Hex color code", max_length=7
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("health", "Health & Fitness"),
                            ("mindfulness", "Mindfulness"),
                            ("productivity", "Productivity"),
                            ("learning", "Learning"),
                            ("social", "Social"),
                            ("creative", "Creative"),
                            ("self_care", "Self Care"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "frequency_type",
                    models.CharField(
                        choices=[
                            ("daily", "Every Day"),
                            ("weekly", "Once per Week"),
                            ("x_per_week", "X Times per Week"),
                            ("specific_days", "Specific Days"),
                        ],
                        default="daily",
                        max_length=15,
                    ),
                ),
                (
                    "times_per_week",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of times per week (for x_per_week frequency)",
                    ),
                ),
                (
                    "specific_days",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated day numbers: 0=Mon, 1=Tue, ..., 6=Sun",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("is_active", models.BooleanField(default=True)),
                ("current_streak", models.PositiveIntegerField(default=0)),
                ("longest_streak", models.PositiveIntegerField(default=0)),
                ("total_completions", models.PositiveIntegerField(default=0)),
                ("last_completed_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "journal_entries",
                    models.ManyToManyField(
                        blank=True, related_name="linked_habits", to="journal.entry"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_active", "name"],
            },
        ),
        migrations.CreateModel(
            name="HabitCheckin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_date", models.DateField(default=django.utils.timezone.now)),
                ("completed", models.BooleanField(default=True)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to="habits.habit",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="habit_checkins",
                        to="journal.entry",
                    ),
                ),
            ],
            options={
                "ordering": ["-check_date"],
            },
        ),
        migrations.AddIndex(
            model_name="habit",
            index=models.Index(
                fields=["user", "is_active"], name="habits_habi_user_id_f5e729_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="habit",
            index=models.Index(
                fields=["user", "category"], name="habits_habi_user_id_35e2ba_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="habitcheckin",
            unique_together={("habit", "check_date")},
        ),
    ]
