# Generated by Django 5.2.9 on 2025-12-30 17:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0014_add_feedback_model"),
        ("journal", "0007_add_geocoded_location"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CycleLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("log_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("period_start", "Period Started"),
                            ("period_end", "Period Ended"),
                            ("symptom", "Symptom Only"),
                            ("note", "Note"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "flow_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("light", "Light"),
                            ("medium", "Medium"),
                            ("heavy", "Heavy"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "symptoms",
                    models.JSONField(
                        blank=True, default=list, help_text="List of symptoms"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cycle_logs",
                        to="journal.entry",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        help_text="Track for self (null) or family member",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cycle_logs",
                        to="accounts.familymember",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cycle_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-log_date"],
                "indexes": [
                    models.Index(
                        fields=["user", "-log_date"],
                        name="wellness_cy_user_id_e8f9b2_idx",
                    ),
                    models.Index(
                        fields=["user", "person", "-log_date"],
                        name="wellness_cy_user_id_48a2f3_idx",
                    ),
                    models.Index(
                        fields=["user", "event_type"],
                        name="wellness_cy_user_id_16f55c_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CyclePrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "predicted_start",
                    models.DateField(help_text="Next predicted period start date"),
                ),
                (
                    "avg_cycle_length",
                    models.PositiveSmallIntegerField(
                        default=28, help_text="Average cycle length in days"
                    ),
                ),
                (
                    "avg_period_length",
                    models.PositiveSmallIntegerField(
                        default=5, help_text="Average period length in days"
                    ),
                ),
                ("last_calculated", models.DateTimeField(auto_now=True)),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cycle_predictions",
                        to="accounts.familymember",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cycle_predictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "person")},
            },
        ),
        migrations.CreateModel(
            name="IntimacyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logged_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Optional rating 1-5", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intimacy_logs",
                        to="journal.entry",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intimacy_logs",
                        to="accounts.familymember",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intimacy_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-logged_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-logged_at"],
                        name="wellness_in_user_id_442073_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PainLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logged_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("head", "Head"),
                            ("neck", "Neck"),
                            ("back", "Back"),
                            ("chest", "Chest"),
                            ("arm", "Arm"),
                            ("leg", "Leg"),
                            ("tooth", "Tooth"),
                            ("stomach", "Stomach"),
                            ("joint", "Joint"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "intensity",
                    models.PositiveSmallIntegerField(
                        help_text="Pain intensity from 1-10"
                    ),
                ),
                (
                    "pain_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sharp", "Sharp"),
                            ("dull", "Dull"),
                            ("throbbing", "Throbbing"),
                            ("burning", "Burning"),
                            ("aching", "Aching"),
                            ("stabbing", "Stabbing"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("brief", "Brief (minutes)"),
                            ("hours", "Hours"),
                            ("all_day", "All Day"),
                            ("ongoing", "Ongoing"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "triggers",
                    models.JSONField(
                        blank=True, default=list, help_text="List of suspected triggers"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entry",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional linked journal entry",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pain_logs",
                        to="journal.entry",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pain_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-logged_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-logged_at"],
                        name="wellness_pa_user_id_5002d4_idx",
                    ),
                    models.Index(
                        fields=["user", "location"],
                        name="wellness_pa_user_id_708c55_idx",
                    ),
                ],
            },
        ),
    ]
