# Generated by Django 5.2.9 on 2026-01-08 21:34

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0002_add_linked_habits"),
        ("journal", "0013_add_pov_approval_workflow"),
        ("wellness", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FitnessGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("weight", "Weight Goal"),
                            ("measurement", "Measurement Goal"),
                            ("cardio_time", "Cardio Time Goal"),
                            ("cardio_distance", "Cardio Distance Goal"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "measurement_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("weight", "Weight"),
                            ("waist", "Waist"),
                            ("chest", "Chest"),
                            ("biceps", "Biceps"),
                            ("thighs", "Thighs"),
                            ("hips", "Hips"),
                            ("body_fat", "Body Fat %"),
                        ],
                        help_text="For weight/measurement goals",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("run", "Running"),
                            ("walk", "Walking"),
                            ("bike", "Cycling"),
                            ("swim", "Swimming"),
                            ("elliptical", "Elliptical"),
                            ("rowing", "Rowing"),
                            ("other", "Other"),
                        ],
                        help_text="For cardio goals",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "target_distance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Target distance for cardio time goals (e.g., 3 miles)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "start_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Starting value when goal was created",
                        max_digits=6,
                    ),
                ),
                (
                    "target_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Target value to achieve",
                        max_digits=6,
                    ),
                ),
                (
                    "current_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Most recent recorded value",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="Unit of measurement (lbs, inches, min:sec, miles)",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(default=datetime.date.today)),
                ("target_date", models.DateField(help_text="Target completion date")),
                ("is_active", models.BooleanField(default=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "linked_goal",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional link to a general goal",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fitness_goals",
                        to="goals.goal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fitness_goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FitnessGoalProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=6)),
                ("logged_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_entries",
                        to="wellness.fitnessgoal",
                    ),
                ),
            ],
            options={
                "ordering": ["-logged_at"],
            },
        ),
        migrations.CreateModel(
            name="BodyMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logged_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Weight in selected unit",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "weight_unit",
                    models.CharField(
                        choices=[("lbs", "Pounds"), ("kg", "Kilograms")],
                        default="lbs",
                        max_length=3,
                    ),
                ),
                (
                    "waist",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Waist at navel",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "chest",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "biceps",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "thighs",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "hips",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "body_fat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Body fat percentage",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "measurement_unit",
                    models.CharField(
                        choices=[("in", "Inches"), ("cm", "Centimeters")],
                        default="in",
                        max_length=2,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entry",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional linked journal entry",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="body_metrics",
                        to="journal.entry",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="body_metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-logged_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-logged_at"],
                        name="wellness_bo_user_id_e23beb_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CardioLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logged_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("run", "Running"),
                            ("walk", "Walking"),
                            ("bike", "Cycling"),
                            ("swim", "Swimming"),
                            ("elliptical", "Elliptical"),
                            ("rowing", "Rowing"),
                            ("other", "Other"),
                        ],
                        default="run",
                        max_length=20,
                    ),
                ),
                (
                    "distance",
                    models.DecimalField(
                        decimal_places=2, help_text="Distance in miles", max_digits=5
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(help_text="Total minutes"),
                ),
                (
                    "duration_seconds",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Additional seconds (0-59)"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entry",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional linked journal entry",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cardio_logs",
                        to="journal.entry",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cardio_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-logged_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-logged_at"],
                        name="wellness_ca_user_id_d16c14_idx",
                    ),
                    models.Index(
                        fields=["user", "activity_type", "-logged_at"],
                        name="wellness_ca_user_id_e39f48_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="fitnessgoal",
            index=models.Index(
                fields=["user", "is_active", "-created_at"],
                name="wellness_fi_user_id_eb7f53_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fitnessgoal",
            index=models.Index(
                fields=["user", "goal_type", "is_active"],
                name="wellness_fi_user_id_775b0e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fitnessgoalprogress",
            index=models.Index(
                fields=["goal", "-logged_at"], name="wellness_fi_goal_id_c725a5_idx"
            ),
        ),
    ]
