# Generated by Django 5.2.9 on 2026-01-08 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "wellness",
            "0002_fitnessgoal_fitnessgoalprogress_bodymetric_cardiolog_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="fitnessgoal",
            name="target_time_minutes",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Target time in minutes (e.g., 26 for 26:00)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fitnessgoal",
            name="target_time_seconds",
            field=models.PositiveSmallIntegerField(
                blank=True, default=0, help_text="Target time seconds (0-59)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="fitnessgoal",
            name="goal_type",
            field=models.CharField(
                choices=[
                    ("weight", "Weight Goal"),
                    ("measurement", "Measurement Goal"),
                    ("cardio", "Cardio Goal"),
                    ("cardio_time", "Cardio Time Goal"),
                    ("cardio_distance", "Cardio Distance Goal"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="fitnessgoal",
            name="target_distance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Target distance (e.g., 3 miles)",
                max_digits=5,
                null=True,
            ),
        ),
    ]
