# Generated by Django 5.2.9 on 2025-12-19 21:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("content", models.TextField()),
                ("word_count", models.IntegerField(default=0)),
                (
                    "mood",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ecstatic", "Ecstatic"),
                            ("happy", "Happy"),
                            ("neutral", "Neutral"),
                            ("sad", "Sad"),
                            ("angry", "Angry"),
                        ],
                        help_text="How are you feeling? (Optional)",
                        max_length=20,
                    ),
                ),
                (
                    "energy",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        help_text="What's your energy level? (Optional)",
                        max_length=20,
                    ),
                ),
                ("entry_date", models.DateField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_analyzed", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Entry",
                "verbose_name_plural": "Entries",
                "ordering": ["-entry_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entries",
                    models.ManyToManyField(
                        blank=True, related_name="tags", to="journal.entry"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="entry",
            index=models.Index(
                fields=["user", "entry_date"], name="journal_ent_user_id_0db6a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entry",
            index=models.Index(
                fields=["user", "is_analyzed"], name="journal_ent_user_id_6c2a49_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entry",
            index=models.Index(
                fields=["user", "created_at"], name="journal_ent_user_id_ddcdf2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together={("user", "name")},
        ),
    ]
