# Generated by Django 5.2.9 on 2025-12-22 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0002_attachment"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntryCapture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "capture_type",
                    models.CharField(
                        choices=[
                            ("book", "Book"),
                            ("watched", "Watched"),
                            ("travel", "Travel"),
                            ("workout", "Workout"),
                            ("person", "Person"),
                            ("place", "Place"),
                            ("meal", "Meal"),
                            ("dream", "Dream"),
                            ("gratitude", "Gratitude"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="captures",
                        to="journal.entry",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["entry", "capture_type"],
                        name="journal_ent_entry_i_a1919a_idx",
                    ),
                    models.Index(
                        fields=["capture_type", "created_at"],
                        name="journal_ent_capture_b7ced8_idx",
                    ),
                ],
            },
        ),
    ]
