# Generated by Django 5.2.9 on 2025-12-22 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0003_entry_capture"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SharedPOV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(help_text="The POV content (markdown)")),
                (
                    "content_hash",
                    models.CharField(
                        help_text="Hash to identify this POV block in the entry",
                        max_length=64,
                    ),
                ),
                (
                    "position_index",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order of this POV in the entry (0-indexed)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authored_povs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_povs",
                        to="journal.entry",
                    ),
                ),
            ],
            options={
                "ordering": ["entry", "position_index"],
            },
        ),
        migrations.CreateModel(
            name="POVReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pov_replies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pov",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="journal.sharedpov",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SharedPOVRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("email_sent", models.BooleanField(default=False)),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pov",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="journal.sharedpov",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_povs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="sharedpov",
            index=models.Index(
                fields=["author", "created_at"], name="journal_sha_author__2ad828_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sharedpov",
            index=models.Index(
                fields=["entry", "position_index"],
                name="journal_sha_entry_i_9a65f9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="povreply",
            index=models.Index(
                fields=["pov", "created_at"], name="journal_pov_pov_id_9793ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sharedpovrecipient",
            index=models.Index(
                fields=["user", "is_read", "created_at"],
                name="journal_sha_user_id_92d73d_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sharedpovrecipient",
            unique_together={("pov", "user")},
        ),
    ]
