# Generated by Django 5.2.9 on 2025-12-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0004_add_pov_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="city",
            field=models.CharField(
                blank=True,
                help_text="City where you're writing from (for weather data)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="entry",
            name="country_code",
            field=models.CharField(
                blank=True,
                default="US",
                help_text="Two-letter country code",
                max_length=2,
            ),
        ),
    ]
