# Generated by Django 5.2.9 on 2025-12-25 17:18

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0005_entry_city_entry_country_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="content",
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name="entry",
            name="title",
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
    ]
