# Generated by Django 5.2.9 on 2025-12-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0006_alter_entry_content_alter_entry_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeocodedLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lng", models.FloatField(blank=True, null=True)),
                ("geocoded_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-geocoded_at"],
            },
        ),
    ]
