# Generated by Django 5.2.9 on 2025-12-31 02:24

import apps.journal.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0007_add_geocoded_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="content",
            field=apps.journal.fields.UserEncryptedTextField(),
        ),
        migrations.AlterField(
            model_name="entry",
            name="title",
            field=apps.journal.fields.UserEncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name="entrycapture",
            name="capture_type",
            field=models.CharField(
                choices=[
                    ("book", "Book"),
                    ("watched", "Watched"),
                    ("travel", "Travel"),
                    ("workout", "Workout"),
                    ("person", "Person"),
                    ("place", "Place"),
                    ("meal", "Meal"),
                    ("dream", "Dream"),
                    ("gratitude", "Gratitude"),
                    ("pain", "Pain"),
                    ("intimacy", "Intimacy"),
                    ("cycle", "Cycle"),
                ],
                max_length=20,
            ),
        ),
    ]
