# Generated by Django 5.2.9 on 2026-01-04 21:30

import apps.journal.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0008_change_to_per_user_encryption"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.journal.models.thumbnail_upload_path,
            ),
        ),
    ]
