# Generated by Django 5.2.9 on 2026-01-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0011_seed_prompt_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="promptcategory",
            name="image_url",
            field=models.URLField(
                blank=True, help_text="Background image URL for the category card"
            ),
        ),
    ]
