# Generated by Django 5.2.9 on 2026-01-05 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0012_add_image_url_to_promptcategory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sharedpovrecipient",
            name="added_to_entry",
            field=models.ForeignKey(
                blank=True,
                help_text="The entry this POV was added to (if approved)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pov_additions",
                to="journal.entry",
            ),
        ),
        migrations.AddField(
            model_name="sharedpovrecipient",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                help_text="Whether recipient has approved adding this POV to their journal",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sharedpovrecipient",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="sharedpovrecipient",
            index=models.Index(
                fields=["user", "approval_status"],
                name="journal_sha_user_id_7d78bd_idx",
            ),
        ),
    ]
