# Generated by Django 5.2.9 on 2025-12-29 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("blog", "0002_add_category"),
        ("journal", "0007_add_geocoded_location"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("description", models.TextField()),
                ("short_description", models.CharField(blank=True, max_length=300)),
                (
                    "icon",
                    models.CharField(
                        default="bi-trophy",
                        help_text="Bootstrap icon class",
                        max_length=50,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6366f1",
                        help_text="Hex color for challenge theme",
                        max_length=7,
                    ),
                ),
                (
                    "cover_image",
                    models.URLField(blank=True, help_text="URL to cover image"),
                ),
                (
                    "cadence",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="daily",
                        max_length=10,
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(
                        help_text="Total number of prompts/days"
                    ),
                ),
                (
                    "badge_id",
                    models.CharField(
                        help_text="Unique badge ID for completion",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "badge_name",
                    models.CharField(help_text="Badge display name", max_length=100),
                ),
                ("badge_icon", models.CharField(default="bi-award", max_length=50)),
                (
                    "badge_tier",
                    models.CharField(
                        choices=[
                            ("challenge", "Challenge"),
                            ("challenge_bronze", "Challenge Bronze"),
                            ("challenge_silver", "Challenge Silver"),
                            ("challenge_gold", "Challenge Gold"),
                        ],
                        default="challenge",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=15,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("requires_premium", models.BooleanField(default=False)),
                ("participant_count", models.PositiveIntegerField(default=0)),
                ("completion_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "blog_post",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional blog post providing context",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="challenges",
                        to="blog.post",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChallengePrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_number",
                    models.PositiveIntegerField(
                        help_text="Day/prompt number (1, 2, 3, etc.)"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "prompt_text",
                    models.TextField(help_text="The journal prompt for this day"),
                ),
                (
                    "guidance",
                    models.TextField(
                        blank=True, help_text="Optional additional guidance or tips"
                    ),
                ),
                ("icon", models.CharField(default="bi-journal-text", max_length=50)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompts",
                        to="challenges.challenge",
                    ),
                ),
            ],
            options={
                "ordering": ["challenge", "day_number"],
            },
        ),
        migrations.CreateModel(
            name="UserChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "start_date",
                    models.DateField(help_text="The date user began the challenge"),
                ),
                (
                    "expected_end_date",
                    models.DateField(
                        help_text="Expected completion date based on cadence"
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("current_day", models.PositiveIntegerField(default=1)),
                ("prompts_completed", models.PositiveIntegerField(default=0)),
                ("last_entry_date", models.DateField(blank=True, null=True)),
                ("missed_days", models.PositiveIntegerField(default=0)),
                ("badge_earned", models.BooleanField(default=False)),
                ("badge_earned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="challenges.challenge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ChallengeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_on_time",
                    models.BooleanField(
                        default=True, help_text="Was this submitted within cadence?"
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge_entries",
                        to="journal.entry",
                    ),
                ),
                (
                    "prompt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_entries",
                        to="challenges.challengeprompt",
                    ),
                ),
                (
                    "user_challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="challenges.userchallenge",
                    ),
                ),
            ],
            options={
                "ordering": ["prompt__day_number"],
            },
        ),
        migrations.AddIndex(
            model_name="challenge",
            index=models.Index(
                fields=["status", "is_featured"], name="challenges__status_fc13d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="challenge",
            index=models.Index(fields=["slug"], name="challenges__slug_85cc59_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="challengeprompt",
            unique_together={("challenge", "day_number")},
        ),
        migrations.AddIndex(
            model_name="userchallenge",
            index=models.Index(
                fields=["user", "status"], name="challenges__user_id_407057_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userchallenge",
            index=models.Index(
                fields=["challenge", "status"], name="challenges__challen_d3b7b1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userchallenge",
            unique_together={("user", "challenge")},
        ),
        migrations.AlterUniqueTogether(
            name="challengeentry",
            unique_together={("user_challenge", "prompt")},
        ),
    ]
