# Generated by Django 5.2.9 on 2025-12-19 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("journal", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EntryAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sentiment_score",
                    models.FloatField(
                        help_text="Polarity score from -1.0 (negative) to 1.0 (positive)"
                    ),
                ),
                (
                    "sentiment_label",
                    models.CharField(
                        help_text="positive, negative, or neutral", max_length=20
                    ),
                ),
                ("detected_mood", models.CharField(max_length=20)),
                (
                    "mood_confidence",
                    models.FloatField(
                        default=0.5, help_text="Confidence score 0.0 to 1.0"
                    ),
                ),
                (
                    "keywords",
                    models.JSONField(
                        default=list, help_text="Top keywords extracted from entry"
                    ),
                ),
                (
                    "themes",
                    models.JSONField(
                        default=list,
                        help_text="Detected themes (work, family, health, etc.)",
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="AI-generated summary of the entry"
                    ),
                ),
                ("analyzed_at", models.DateTimeField(auto_now=True)),
                (
                    "entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="journal.entry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entry Analysis",
                "verbose_name_plural": "Entry Analyses",
            },
        ),
        migrations.CreateModel(
            name="MonthlySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                ("entry_count", models.IntegerField(default=0)),
                ("total_words", models.IntegerField(default=0)),
                ("avg_sentiment", models.FloatField(default=0.0)),
                ("dominant_mood", models.CharField(blank=True, max_length=20)),
                (
                    "mood_distribution",
                    models.JSONField(
                        default=dict,
                        help_text='{"ecstatic": 2, "happy": 15, "neutral": 10, "sad": 3, "angry": 1}',
                    ),
                ),
                ("top_themes", models.JSONField(default=list)),
                ("best_day_id", models.IntegerField(blank=True, null=True)),
                ("best_day_sentiment", models.FloatField(blank=True, null=True)),
                ("worst_day_id", models.IntegerField(blank=True, null=True)),
                ("worst_day_sentiment", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month"],
                "unique_together": {("user", "year", "month")},
            },
        ),
        migrations.CreateModel(
            name="YearlyReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("total_entries", models.IntegerField(default=0)),
                ("total_words", models.IntegerField(default=0)),
                ("avg_sentiment", models.FloatField(default=0.0)),
                ("dominant_mood", models.CharField(blank=True, max_length=20)),
                (
                    "mood_distribution",
                    models.JSONField(
                        default=dict, help_text="Full year mood breakdown"
                    ),
                ),
                (
                    "monthly_trend",
                    models.JSONField(
                        default=list,
                        help_text="[{month: 1, sentiment: 0.12, mood: 'happy'}, ...]",
                    ),
                ),
                (
                    "top_themes",
                    models.JSONField(default=list, help_text="Top themes for the year"),
                ),
                (
                    "theme_sentiments",
                    models.JSONField(
                        default=dict, help_text="Sentiment score per theme"
                    ),
                ),
                (
                    "highlights",
                    models.JSONField(
                        default=list, help_text="Top 10 best days with previews"
                    ),
                ),
                (
                    "lowlights",
                    models.JSONField(
                        default=list, help_text="Top 10 challenging days with previews"
                    ),
                ),
                (
                    "narrative_summary",
                    models.TextField(
                        blank=True, help_text="AI-generated year-in-review narrative"
                    ),
                ),
                (
                    "insights",
                    models.JSONField(
                        default=list, help_text="Key observations about the year"
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yearly_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-year"],
                "unique_together": {("user", "year")},
            },
        ),
    ]
