# Generated by Django 5.2.9 on 2025-12-22 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0001_initial"),
        ("journal", "0003_entry_capture"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaptureSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("month", models.IntegerField(blank=True, null=True)),
                ("capture_type", models.CharField(max_length=20)),
                ("count", models.IntegerField(default=0)),
                ("data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capture_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "capture_type", "year"],
                        name="analytics_c_user_id_47d79b_idx",
                    )
                ],
                "unique_together": {("user", "year", "month", "capture_type")},
            },
        ),
        migrations.CreateModel(
            name="TrackedBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("normalized_title", models.CharField(db_index=True, max_length=300)),
                ("author", models.CharField(blank=True, max_length=200)),
                (
                    "normalized_author",
                    models.CharField(blank=True, db_index=True, max_length=200),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("want_to_read", "Want to Read"),
                            ("reading", "Currently Reading"),
                            ("finished", "Finished"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="reading",
                        max_length=20,
                    ),
                ),
                ("started_date", models.DateField(blank=True, null=True)),
                ("finished_date", models.DateField(blank=True, null=True)),
                ("current_page", models.IntegerField(default=0)),
                ("total_pages", models.IntegerField(blank=True, null=True)),
                ("rating", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "captures",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tracked_book",
                        to="journal.entrycapture",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracked_books",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="analytics_t_user_id_d91411_idx"
                    ),
                    models.Index(
                        fields=["user", "finished_date"],
                        name="analytics_t_user_id_1ab6ad_idx",
                    ),
                ],
                "unique_together": {("user", "normalized_title", "normalized_author")},
            },
        ),
        migrations.CreateModel(
            name="TrackedPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("normalized_name", models.CharField(db_index=True, max_length=200)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("family", "Family"),
                            ("friend", "Friend"),
                            ("colleague", "Colleague"),
                            ("acquaintance", "Acquaintance"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("mention_count", models.IntegerField(default=0)),
                ("first_mention_date", models.DateField(blank=True, null=True)),
                ("last_mention_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "captures",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tracked_person",
                        to="journal.entrycapture",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracked_people",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-mention_count", "name"],
                "unique_together": {("user", "normalized_name")},
            },
        ),
    ]
