# Generated by Django 5.2.9 on 2025-12-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0002_capturesnapshot_trackedbook_trackedperson"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackedperson",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="trackedperson",
            name="sentiment",
            field=models.CharField(
                choices=[
                    ("love", "Love"),
                    ("like", "Like"),
                    ("neutral", "Neutral"),
                    ("dislike", "Dislike"),
                    ("hate", "Hate"),
                ],
                default="neutral",
                max_length=20,
            ),
        ),
    ]
