# Generated by Django 5.2.9 on 2025-12-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0003_add_person_sentiment_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="entryanalysis",
            name="humidity",
            field=models.IntegerField(
                blank=True, help_text="Humidity percentage", null=True
            ),
        ),
        migrations.AddField(
            model_name="entryanalysis",
            name="moon_illumination",
            field=models.FloatField(
                blank=True, help_text="Moon illumination 0.0 to 1.0", null=True
            ),
        ),
        migrations.AddField(
            model_name="entryanalysis",
            name="moon_phase",
            field=models.CharField(
                blank=True,
                help_text="Moon phase name: new_moon, waxing_crescent, first_quarter, etc.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="entryanalysis",
            name="temperature",
            field=models.FloatField(
                blank=True, help_text="Temperature in Celsius", null=True
            ),
        ),
        migrations.AddField(
            model_name="entryanalysis",
            name="weather_condition",
            field=models.CharField(
                blank=True,
                help_text="Main weather condition: clear, clouds, rain, etc.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="entryanalysis",
            name="weather_description",
            field=models.CharField(
                blank=True, help_text="Detailed weather description", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="entryanalysis",
            name="weather_icon",
            field=models.CharField(
                blank=True, help_text="OpenWeatherMap icon code", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="entryanalysis",
            name="zodiac_sign",
            field=models.CharField(
                blank=True,
                help_text="User's zodiac sign: aries, taurus, etc.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="trackedperson",
            name="relationship",
            field=models.CharField(
                choices=[
                    ("partner", "Partner"),
                    ("family", "Family"),
                    ("friend", "Friend"),
                    ("colleague", "Colleague"),
                    ("acquaintance", "Acquaintance"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
