# Generated by Django 5.2.9 on 2025-12-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0004_entryanalysis_humidity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entryanalysis",
            name="weather_location",
            field=models.CharField(
                blank=True,
                help_text="City and country where weather was fetched from",
                max_length=150,
            ),
        ),
    ]
