# Generated by Django 5.2.9 on 2025-12-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0005_entryanalysis_weather_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="yearlyreview",
            name="theme_entry_counts",
            field=models.JSONField(
                default=dict, help_text="Number of entries per theme"
            ),
        ),
    ]
