# Generated by Django 5.2.9 on 2025-12-22 03:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("journal", "0002_attachment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Describe your goal in detail"
                    ),
                ),
                (
                    "success_criteria",
                    models.TextField(
                        blank=True,
                        help_text="How will you know when this goal is achieved?",
                    ),
                ),
                (
                    "target_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Target number (e.g., 10 for '10 books')",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "current_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Current progress value",
                        max_digits=10,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="Unit of measurement (e.g., 'books', 'miles', 'pounds')",
                        max_length=50,
                    ),
                ),
                (
                    "why_achievable",
                    models.TextField(
                        blank=True, help_text="Why is this goal achievable for you?"
                    ),
                ),
                (
                    "relevance",
                    models.TextField(
                        blank=True, help_text="Why is this goal important to you?"
                    ),
                ),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "due_date",
                    models.DateField(
                        blank=True,
                        help_text="When do you want to achieve this goal?",
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("health", "Health & Fitness"),
                            ("career", "Career & Professional"),
                            ("education", "Education & Learning"),
                            ("finance", "Finance & Money"),
                            ("relationships", "Relationships"),
                            ("personal", "Personal Development"),
                            ("creative", "Creative & Hobbies"),
                            ("other", "Other"),
                        ],
                        default="personal",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("on_hold", "On Hold"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="not_started",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "journal_entries",
                    models.ManyToManyField(
                        blank=True, related_name="linked_goals", to="journal.entry"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GoalProgressLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, help_text="New progress value", max_digits=10
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, help_text="Optional note about this progress update"
                    ),
                ),
                ("logged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_logs",
                        to="goals.goal",
                    ),
                ),
            ],
            options={
                "ordering": ["-logged_at"],
            },
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="goals.goal",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(
                fields=["user", "status"], name="goals_goal_user_id_7ad9fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(
                fields=["user", "category"], name="goals_goal_user_id_5b224d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(
                fields=["user", "due_date"], name="goals_goal_user_id_b30fa5_idx"
            ),
        ),
    ]
