# Generated by Django 5.2.9 on 2025-12-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goals", "0001_initial"),
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="linked_habits",
            field=models.ManyToManyField(
                blank=True,
                help_text="Habits that contribute to achieving this goal",
                related_name="linked_goals",
                to="habits.habit",
            ),
        ),
    ]
